/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdateRouteImport } from './routes/update'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DestroyRouteImport } from './routes/destroy'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as DocsInstallSlugRouteImport } from './routes/docs.install.$slug'

const UpdateRoute = UpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DestroyRoute = DestroyRouteImport.update({
  id: '/destroy',
  path: '/destroy',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallSlugRoute = DocsInstallSlugRouteImport.update({
  id: '/install/$slug',
  path: '/install/$slug',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/deploy': typeof DeployRoute
  '/destroy': typeof DestroyRoute
  '/docs': typeof DocsRouteWithChildren
  '/update': typeof UpdateRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/docs/install/$slug': typeof DocsInstallSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/deploy': typeof DeployRoute
  '/destroy': typeof DestroyRoute
  '/update': typeof UpdateRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/docs': typeof DocsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/docs/install/$slug': typeof DocsInstallSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/deploy': typeof DeployRoute
  '/destroy': typeof DestroyRoute
  '/docs': typeof DocsRouteWithChildren
  '/update': typeof UpdateRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/docs/install/$slug': typeof DocsInstallSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/deploy'
    | '/destroy'
    | '/docs'
    | '/update'
    | '/guides/$slug'
    | '/docs/'
    | '/guides/'
    | '/docs/install/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/deploy'
    | '/destroy'
    | '/update'
    | '/guides/$slug'
    | '/docs'
    | '/guides'
    | '/docs/install/$slug'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/deploy'
    | '/destroy'
    | '/docs'
    | '/update'
    | '/guides/$slug'
    | '/docs/'
    | '/guides/'
    | '/docs/install/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  DeployRoute: typeof DeployRoute
  DestroyRoute: typeof DestroyRoute
  DocsRoute: typeof DocsRouteWithChildren
  UpdateRoute: typeof UpdateRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update': {
      id: '/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof UpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destroy': {
      id: '/destroy'
      path: '/destroy'
      fullPath: '/destroy'
      preLoaderRoute: typeof DestroyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/install/$slug': {
      id: '/docs/install/$slug'
      path: '/install/$slug'
      fullPath: '/docs/install/$slug'
      preLoaderRoute: typeof DocsInstallSlugRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsInstallSlugRoute: typeof DocsInstallSlugRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsInstallSlugRoute: DocsInstallSlugRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  DeployRoute: DeployRoute,
  DestroyRoute: DestroyRoute,
  DocsRoute: DocsRouteWithChildren,
  UpdateRoute: UpdateRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
