/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalSitesRouteImport } from './routes/portal.sites'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalSiteSiteIdRouteImport } from './routes/portal.site.$siteId'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSitesRoute = PortalSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => PortalRoute,
} as any).lazy(() => import('./routes/portal.sites.lazy').then((d) => d.Route))
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSiteSiteIdRoute = PortalSiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => PortalRoute,
} as any).lazy(() =>
  import('./routes/portal.site.$siteId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/sites': typeof PortalSitesRoute
  '/portal/site/$siteId': typeof PortalSiteSiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/sites': typeof PortalSitesRoute
  '/portal/site/$siteId': typeof PortalSiteSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/sites': typeof PortalSitesRoute
  '/portal/site/$siteId': typeof PortalSiteSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/portal/settings'
    | '/portal/sites'
    | '/portal/site/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/portal/settings'
    | '/portal/sites'
    | '/portal/site/$siteId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/portal/settings'
    | '/portal/sites'
    | '/portal/site/$siteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/sites': {
      id: '/portal/sites'
      path: '/sites'
      fullPath: '/portal/sites'
      preLoaderRoute: typeof PortalSitesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/site/$siteId': {
      id: '/portal/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/portal/site/$siteId'
      preLoaderRoute: typeof PortalSiteSiteIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalSitesRoute: typeof PortalSitesRoute
  PortalSiteSiteIdRoute: typeof PortalSiteSiteIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalSettingsRoute: PortalSettingsRoute,
  PortalSitesRoute: PortalSitesRoute,
  PortalSiteSiteIdRoute: PortalSiteSiteIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
